apiVersion: apps/v1
kind: deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment-1
  template:
    metadata:
      labels:
        name: deployment-1
    spec:
      containers:
      - name: busybox-container
        image: busybox999
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes! && sleep 3600